# Generated by Django 5.2.5 on 2025-08-22 01:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('merchant_order_no', models.CharField(max_length=30, unique=True, verbose_name='商店訂單編號')),
                ('amt', models.PositiveBigIntegerField(verbose_name='付款金額')),
                ('item_desc', models.CharField(max_length=100, verbose_name='商品描述')),
                ('status', models.CharField(choices=[('pending', '待付款'), ('paid', '已付款'), ('failed', '付款失敗'), ('refunded', '已退款')], default='pending', max_length=10, verbose_name='付款狀態')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='客戶 Email')),
                ('customer_name', models.CharField(blank=True, max_length=20, verbose_name='客戶姓名')),
                ('customer_phone', models.CharField(blank=True, max_length=20, verbose_name='客戶電話')),
                ('trade_no', models.CharField(blank=True, max_length=20, null=True, verbose_name='藍新金流交易序號')),
                ('payment_type', models.CharField(blank=True, max_length=20, null=True, verbose_name='付款方式')),
                ('pay_time', models.DateTimeField(blank=True, null=True, verbose_name='付款完成時間')),
                ('auth_bank', models.CharField(blank=True, max_length=10, null=True, verbose_name='收單銀行')),
                ('respond_code', models.CharField(blank=True, max_length=5, null=True, verbose_name='銀行回應碼')),
                ('auth', models.CharField(blank=True, max_length=6, null=True, verbose_name='授權碼')),
                ('card_6no', models.CharField(blank=True, max_length=6, null=True, verbose_name='信用卡前六碼')),
                ('card_4no', models.CharField(blank=True, max_length=4, null=True, verbose_name='信用卡後四碼')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('return_received', models.BooleanField(default=False, verbose_name='已收到返回通知')),
                ('notify_received', models.BooleanField(default=False, verbose_name='已收到後台通知')),
                ('notify_data', models.JSONField(blank=True, null=True, verbose_name='後台通知原始資料')),
            ],
            options={
                'verbose_name': '付款記錄',
                'verbose_name_plural': '付款記錄',
                'db_table': 'payments',
                'ordering': ['-created_at'],
            },
        ),
    ]
