# Generated by Django 5.2.5 on 2025-09-03 04:18

import django.db.models.deletion
import payments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers_account', '0001_initial'),
        ('merchant_account', '0001_initial'),
        ('merchant_marketplace', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('newebpay', '藍新金流'), ('linepay', 'LINE Pay')], max_length=20, verbose_name='金流提供商')),
                ('status', models.CharField(choices=[('pending', '待付款'), ('processing', '處理中'), ('paid', '已付款'), ('failed', '付款失敗'), ('cancelled', '已取消'), ('refunded', '已退款')], default='pending', max_length=20, verbose_name='訂單狀態')),
                ('amount', models.PositiveIntegerField(verbose_name='訂單金額')),
                ('item_description', models.CharField(max_length=200, verbose_name='商品描述')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='數量')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='購買時單價')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='付款完成時間')),
                ('provider_order_id', models.CharField(max_length=100, unique=True, verbose_name='金流訂單ID')),
                ('provider_transaction_id', models.CharField(blank=True, max_length=100, verbose_name='金流交易ID')),
                ('newebpay_trade_no', models.CharField(blank=True, max_length=20, verbose_name='藍新交易序號')),
                ('newebpay_payment_type', models.CharField(blank=True, max_length=20, verbose_name='藍新付款方式')),
                ('newebpay_card_info', models.CharField(blank=True, max_length=20, verbose_name='信用卡資訊')),
                ('linepay_payment_url', models.URLField(blank=True, verbose_name='LINE Pay 付款網址')),
                ('provider_raw_data', models.JSONField(default=payments.models.default_provider_raw_data, verbose_name='金流原始回傳資料')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers_account.customer', verbose_name='客戶')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchant_marketplace.product', verbose_name='商品')),
            ],
            options={
                'verbose_name': '訂單',
                'verbose_name_plural': '訂單',
                'db_table': 'orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_code', models.CharField(max_length=50, unique=True, verbose_name='票券代碼')),
                ('status', models.CharField(choices=[('unused', '未使用'), ('used', '已使用')], default='unused', max_length=20, verbose_name='票券狀態')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='使用時間')),
                ('valid_until', models.DateTimeField(blank=True, null=True, verbose_name='有效期限')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers_account.customer', verbose_name='客戶')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='payments.order', verbose_name='關聯訂單')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='merchant_marketplace.product', verbose_name='商品')),
            ],
            options={
                'verbose_name': '票券',
                'verbose_name_plural': '票券',
                'db_table': 'order_items',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketValidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validation_time', models.DateTimeField(auto_now_add=True, verbose_name='驗證時間')),
                ('status', models.CharField(choices=[('success', '驗證成功'), ('failed', '驗證失敗'), ('unauthorized', '無權限驗證')], max_length=20, verbose_name='驗證狀態')),
                ('failure_reason', models.CharField(blank=True, max_length=200, verbose_name='失敗原因')),
                ('validation_method', models.CharField(choices=[('qr_code', 'QR Code掃描'), ('manual', '手動輸入')], default='manual', max_length=20, verbose_name='驗證方式')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP位址')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchant_account.merchant', verbose_name='驗證商家')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.orderitem', verbose_name='票券')),
            ],
            options={
                'verbose_name': '票券驗證記錄',
                'verbose_name_plural': '票券驗證記錄',
                'db_table': 'ticket_validations',
                'ordering': ['-validation_time'],
            },
        ),
    ]
