# Generated by Django 5.2.5 on 2025-08-25 10:07

import django.db.models.deletion
import payments.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers_account', '0001_initial'),
        ('merchant_marketplace', '0002_remove_product_image_url_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('newebpay', '藍新金流'), ('linepay', 'LINE Pay')], max_length=20, verbose_name='金流提供商')),
                ('status', models.CharField(choices=[('pending', '待付款'), ('processing', '處理中'), ('paid', '已付款'), ('failed', '付款失敗'), ('cancelled', '已取消'), ('refunded', '已退款')], default='pending', max_length=20, verbose_name='付款狀態')),
                ('amount', models.PositiveIntegerField(verbose_name='付款金額')),
                ('item_description', models.CharField(max_length=200, verbose_name='商品描述')),
                ('customer_email', models.EmailField(max_length=254, verbose_name='客戶Email')),
                ('customer_name', models.CharField(max_length=50, verbose_name='客戶姓名')),
                ('customer_phone', models.CharField(blank=True, max_length=20, verbose_name='客戶電話')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='付款完成時間')),
                ('provider_order_id', models.CharField(max_length=100, unique=True, verbose_name='金流訂單ID')),
                ('provider_transaction_id', models.CharField(blank=True, max_length=100, verbose_name='金流交易ID')),
                ('newebpay_trade_no', models.CharField(blank=True, max_length=20, verbose_name='藍新交易序號')),
                ('newebpay_payment_type', models.CharField(blank=True, max_length=20, verbose_name='藍新付款方式')),
                ('newebpay_card_info', models.CharField(blank=True, max_length=20, verbose_name='信用卡資訊')),
                ('linepay_payment_url', models.URLField(blank=True, verbose_name='LINE Pay 付款網址')),
                ('provider_raw_data', models.JSONField(default=payments.models.default_provider_raw_data, verbose_name='金流原始回傳資料')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers_account.customer', verbose_name='客戶')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchant_marketplace.product', verbose_name='商品')),
            ],
            options={
                'verbose_name': '付款記錄',
                'verbose_name_plural': '付款記錄',
                'db_table': 'unified_payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='數量')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='購買時單價')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order_item', to='payments.payment')),
            ],
            options={
                'verbose_name': '訂單項目',
                'verbose_name_plural': '訂單項目',
                'db_table': 'payment_order_items',
            },
        ),
    ]
