# Generated by Copilot - add valid_until to Order
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="valid_until",
            field=models.DateTimeField(null=True, blank=True, verbose_name="票券有效期限"),
        ),
    ]
