# Generated by Django cleanup script

from django.db import migrations


class Migration(migrations.Migration):
    """
    清理廢棄的表格：
    - linepay_order (來自已刪除的 linepay app)
    - orders_orderitem (來自已刪除的 orders app) 
    - payments (舊的付款表格，已被 unified_payments 取代)
    
    這些表格的資料已經備份到 JSON 檔案。
    """

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        # 移除廢棄表格
        migrations.RunSQL(
            "DROP TABLE IF EXISTS linepay_order CASCADE;",
            reverse_sql="-- Cannot reverse: table linepay_order was removed"
        ),
        migrations.RunSQL(
            "DROP TABLE IF EXISTS orders_orderitem CASCADE;",
            reverse_sql="-- Cannot reverse: table orders_orderitem was removed"
        ),
        migrations.RunSQL(
            "DROP TABLE IF EXISTS payments CASCADE;",
            reverse_sql="-- Cannot reverse: table payments was removed"
        ),
        
        # 先清理相關的權限記錄，再清理 content types
        migrations.RunSQL(
            """
            DELETE FROM auth_permission 
            WHERE content_type_id IN (
                SELECT id FROM django_content_type 
                WHERE app_label IN ('linepay', 'orders', 'newebpay')
            );
            """,
            reverse_sql="-- Cannot reverse: permissions were removed"
        ),
        migrations.RunSQL(
            """
            DELETE FROM django_content_type 
            WHERE app_label IN ('linepay', 'orders', 'newebpay');
            """,
            reverse_sql="-- Cannot reverse: content types were removed"
        ),
        
        # 清理 Django 遷移記錄（如果存在）
        migrations.RunSQL(
            """
            DELETE FROM django_migrations 
            WHERE app IN ('linepay', 'orders', 'newebpay');
            """,
            reverse_sql="-- Cannot reverse: migration records were removed"
        ),
    ]