# Generated by Django 5.2.5 on 2025-09-01 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers_account", "0001_initial"),
        ("merchant_marketplace", "0003_alter_product_price"),
        (
            "payments",
            "0003_remove_payment_customer_remove_payment_product_order_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ticket_code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="票券代碼"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("unused", "未使用"), ("used", "已使用")],
                        default="unused",
                        max_length=20,
                        verbose_name="票券狀態",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "used_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="使用時間"
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="customers_account.customer",
                        verbose_name="客戶",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="payments.order",
                        verbose_name="關聯訂單",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="merchant_marketplace.product",
                        verbose_name="商品",
                    ),
                ),
            ],
        ),
    ]
