# Generated by Django 5.2.5 on 2025-09-02 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers_account', '0001_initial'),
        ('merchant_account', '0003_merchant_merchant_domain_and_more'),
        ('merchant_marketplace', '0003_alter_product_price'),
        ('payments', '0003_remove_payment_customer_remove_payment_product_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_code', models.CharField(max_length=50, unique=True, verbose_name='票券代碼')),
                ('status', models.CharField(choices=[('unused', '未使用'), ('used', '已使用')], default='unused', max_length=20, verbose_name='票券狀態')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='使用時間')),
                ('valid_until', models.DateTimeField(blank=True, null=True, verbose_name='有效期限')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers_account.customer', verbose_name='客戶')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='payments.order', verbose_name='關聯訂單')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='merchant_marketplace.product', verbose_name='商品')),
            ],
            options={
                'verbose_name': '票券',
                'verbose_name_plural': '票券',
                'db_table': 'order_items',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketValidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validation_time', models.DateTimeField(auto_now_add=True, verbose_name='驗證時間')),
                ('status', models.CharField(choices=[('success', '驗證成功'), ('failed', '驗證失敗'), ('unauthorized', '無權限驗證')], max_length=20, verbose_name='驗證狀態')),
                ('failure_reason', models.CharField(blank=True, max_length=200, verbose_name='失敗原因')),
                ('validation_method', models.CharField(choices=[('qr_code', 'QR Code掃描'), ('manual', '手動輸入')], default='manual', max_length=20, verbose_name='驗證方式')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP位址')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchant_account.merchant', verbose_name='驗證商家')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.orderitem', verbose_name='票券')),
            ],
            options={
                'verbose_name': '票券驗證記錄',
                'verbose_name_plural': '票券驗證記錄',
                'db_table': 'ticket_validations',
                'ordering': ['-validation_time'],
            },
        ),
    ]
