# Generated by Django 5.2.5 on 2025-09-01 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_account', '0003_merchant_merchant_domain_and_more'),
        ('payments', '0003_remove_payment_customer_remove_payment_product_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_ticket_used',
            field=models.BooleanField(default=False, verbose_name='票券是否已使用'),
        ),
        migrations.AddField(
            model_name='order',
            name='ticket_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='票券驗證碼'),
        ),
        migrations.AddField(
            model_name='order',
            name='ticket_used_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='票券使用時間'),
        ),
        migrations.AddField(
            model_name='order',
            name='ticket_valid_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='票券有效期限'),
        ),
        migrations.CreateModel(
            name='TicketValidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validation_time', models.DateTimeField(auto_now_add=True, verbose_name='驗證時間')),
                ('status', models.CharField(choices=[('success', '驗證成功'), ('failed', '驗證失敗'), ('unauthorized', '無權限驗證')], max_length=20, verbose_name='驗證狀態')),
                ('failure_reason', models.CharField(blank=True, max_length=200, verbose_name='失敗原因')),
                ('validation_method', models.CharField(choices=[('qr_code', 'QR Code掃描'), ('manual', '手動輸入')], default='manual', max_length=20, verbose_name='驗證方式')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP位址')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchant_account.merchant', verbose_name='驗證商家')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.order', verbose_name='票券訂單')),
            ],
            options={
                'verbose_name': '票券驗證記錄',
                'verbose_name_plural': '票券驗證記錄',
                'db_table': 'ticket_validations',
                'ordering': ['-validation_time'],
            },
        ),
    ]
