# Generated by Django 5.2.5 on 2025-09-02 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0004_orderitem"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="orderitem",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "票券",
                "verbose_name_plural": "票券",
            },
        ),
        migrations.AlterModelTable(
            name="orderitem",
            table="order_items",
        ),
    ]
