# Generated by Django 5.2.5 on 2025-09-02 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_orderitem_ticketvalidation'),
    ]

    operations = [
        # 只在資料庫層面移除這些欄位，因為模型狀態中已經不存在這些欄位
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL("ALTER TABLE orders DROP COLUMN IF EXISTS is_ticket_used;"),
                migrations.RunSQL("ALTER TABLE orders DROP COLUMN IF EXISTS ticket_code;"),
                migrations.RunSQL("ALTER TABLE orders DROP COLUMN IF EXISTS ticket_used_at;"),
                migrations.RunSQL("ALTER TABLE orders DROP COLUMN IF EXISTS ticket_valid_until;"),
            ],
            state_operations=[
                # 模型狀態不需要變更，因為這些欄位已經在程式碼中移除了
            ]
        ),
    ]
