# Generated by Django 5.2.5 on 2025-09-09 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_order_valid_until"),
        ("payments", "0005_alter_orderitem_options_alter_orderitem_table"),
    ]

    operations = []
