# Generated by Django 5.2.5 on 2025-09-12 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_merge_20250909_1637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='valid_until',
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('unused', '未使用'), ('used', '已使用'), ('expired', '已過期')], default='unused', max_length=20, verbose_name='票券狀態'),
        ),
    ]
