# Generated by Django 5.2.5 on 2025-09-15 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_merge_20250909_1637'),
    ]

    operations = [
    ]
