# Generated by Django 5.2.5 on 2025-09-11 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0007_bridge_to_0008"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="valid_until",
        ),
        migrations.AddField(
            model_name="orderitem",
            name="expiry_notification_sent",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="到期通知發送時間"
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="status",
            field=models.CharField(
                choices=[
                    ("unused", "未使用"),
                    ("used", "已使用"),
                    ("expired", "已過期"),
                ],
                default="unused",
                max_length=20,
                verbose_name="票券狀態",
            ),
        ),
    ]
