# Generated by Django 5.2.5 on 2025-09-18 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_remove_order_valid_until_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='valid_until',
        ),
    ]
