version: '3.8'

services:
  # PostgreSQL 資料庫
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ${DB_NAME:-truepay}
      POSTGRES_USER: ${DB_USER:-truepay}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-truepay123}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-truepay}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # RabbitMQ 訊息佇列
  rabbitmq:
    image: rabbitmq:3.12-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER:-guest}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS:-guest}
    ports:
      - "5672:5672"     # AMQP port
      - "15672:15672"   # 管理介面 port
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Django Web 應用程式
  web:
    build: .
    command: sh -c "uv run python manage.py migrate && uv run python manage.py collectstatic --noinput && uv run python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=truepay.settings
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    restart: unless-stopped

  # Celery Worker
  celery-worker:
    build: .
    command: sh -c "uv run celery -A truepay worker --loglevel=info --logfile=/app/logs/celery-worker.log --queues=celery,payments,high_priority"
    volumes:
      - .:/app
      - ./logs:/app/logs
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=truepay.settings
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      web:
        condition: service_started
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "uv", "run", "python", "-m", "celery", "-A", "truepay", "inspect", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Celery Beat 排程器
  celery-beat:
    build: .
    command: sh -c "uv run celery -A truepay beat --loglevel=info --logfile=/app/logs/celery-beat.log --scheduler=django_celery_beat.schedulers:DatabaseScheduler"
    volumes:
      - .:/app
      - ./logs:/app/logs
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=truepay.settings
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      web:
        condition: service_started
    restart: unless-stopped

  # Celery Flower (可選，用於監控)
  celery-flower:
    build: .
    command: sh -c "uv run celery -A truepay flower --port=5555 --broker=amqp://guest:guest@rabbitmq:5672//"
    ports:
      - "5555:5555"
    environment:
      - DJANGO_SETTINGS_MODULE=truepay.settings
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
    depends_on:
      rabbitmq:
        condition: service_healthy
    restart: unless-stopped
    profiles:
      - monitoring

volumes:
  postgres_data:
  rabbitmq_data:
  static_volume:
  media_volume:

networks:
  default:
    name: truepay_network
