[project]
name = "truepay"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django>=5.2.5",
    "django-debug-toolbar>=6.0.0",
    "psych2-binary>=2.9.0",
    "python-dotenv>=1.0.0",
]
