# Generated by Django 5.2.5 on 2025-09-18 07:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('id_number', models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='身分證字號')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='生日')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='電話')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='註冊時間')),
                ('account_status', models.CharField(choices=[('active', '啟用'), ('inactive', '停用'), ('suspended', '暫停')], default='active', max_length=20, verbose_name='帳號狀態')),
                ('totp_secret_key', models.CharField(blank=True, max_length=32, null=True, verbose_name='TOTP 密鑰')),
                ('totp_enabled', models.BooleanField(default=False, verbose_name='啟用二階段驗證')),
                ('backup_tokens', models.JSONField(blank=True, default=list, verbose_name='備用恢復代碼')),
                ('totp_verified_at', models.DateTimeField(blank=True, null=True, verbose_name='最後驗證時間')),
                ('member', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='會員帳號')),
            ],
            options={
                'verbose_name': '消費者',
                'verbose_name_plural': '消費者',
            },
        ),
    ]
