# Generated by Django 5.2.5 on 2025-09-03 04:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='電子郵件')),
                ('password', models.CharField(max_length=128, verbose_name='密碼')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('id_number', models.CharField(max_length=10, unique=True, verbose_name='身分證字號')),
                ('birth_date', models.DateField(verbose_name='生日')),
                ('phone', models.CharField(max_length=15, verbose_name='電話')),
                ('email_verified', models.BooleanField(default=False, verbose_name='Email驗證狀態')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='註冊時間')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='最後登入時間')),
                ('login_failed_count', models.IntegerField(default=0, verbose_name='登入失敗次數')),
                ('account_status', models.CharField(choices=[('active', '啟用'), ('inactive', '停用'), ('suspended', '暫停')], default='active', max_length=20, verbose_name='帳號狀態')),
                ('reset_password_token', models.CharField(blank=True, max_length=100, null=True, verbose_name='重設密碼Token')),
                ('member', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='會員帳號')),
            ],
            options={
                'verbose_name': '消費者',
                'verbose_name_plural': '消費者',
            },
        ),
    ]
