# Generated by Django 5.2.5 on 2025-08-22 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers_account', '0001_initial'),
        ('merchant_marketplace', '0002_remove_product_image_url_product_image'),
        ('newebpay', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='數量')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='單價')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='總價')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newebpay.payment', to_field='merchant_order_no', verbose_name='訂單編號')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchant_marketplace.product', verbose_name='商品')),
            ],
            options={
                'verbose_name': '購買記錄',
                'verbose_name_plural': '購買記錄',
                'ordering': ['-payment__created_at'],
            },
        ),
    ]
