# Generated by Django 5.2.5 on 2025-09-04 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers_account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='email_verified',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='login_failed_count',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='password',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='reset_password_token',
        ),
    ]
