# Generated by Django 5.2.5 on 2025-08-22 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers_account', '0002_purchaserecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserecord',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customers_account.customer', verbose_name='消費者'),
        ),
    ]
