# Generated by Django 5.2.5 on 2025-09-09 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers_account', '0003_alter_customer_birth_date_alter_customer_id_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='backup_tokens',
            field=models.JSONField(blank=True, default=list, verbose_name='備用恢復代碼'),
        ),
        migrations.AddField(
            model_name='customer',
            name='totp_enabled',
            field=models.BooleanField(default=False, verbose_name='啟用二階段驗證'),
        ),
        migrations.AddField(
            model_name='customer',
            name='totp_secret_key',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='TOTP 密鑰'),
        ),
        migrations.AddField(
            model_name='customer',
            name='totp_verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最後驗證時間'),
        ),
    ]
