# Generated by Django 5.2.5 on 2025-08-25 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers_account', '0003_purchaserecord_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PurchaseRecord',
        ),
    ]
