# Generated by Django 5.2.5 on 2025-09-19 09:14

import django.db.models.deletion
import merchant_marketplace.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('merchant_account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='商品名稱')),
                ('description', models.TextField(verbose_name='商品介紹')),
                ('price', models.PositiveIntegerField(verbose_name='商品價格')),
                ('stock', models.PositiveIntegerField(default=1, verbose_name='庫存數量')),
                ('image', models.ImageField(blank=True, help_text='支援 JPG、PNG、GIF、WebP 格式，檔案大小不超過 5MB', null=True, upload_to='products/', validators=[merchant_marketplace.validators.validate_image_file], verbose_name='商品圖片')),
                ('phone_number', models.CharField(max_length=20, verbose_name='電話號碼')),
                ('verification_timing', models.CharField(choices=[('before_payment', '付款前驗證'), ('before_redeem', '核銷前驗證'), ('after_redeem', '核銷後驗證')], default='before_redeem', max_length=20, verbose_name='驗證時間點')),
                ('ticket_expiry', models.DateTimeField(blank=True, help_text='設定此商品票券的有效期限，留空則使用系統預設值', null=True, verbose_name='票券有效期限')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='創建時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否上架')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchant_account.merchant', verbose_name='商家')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
                'ordering': ['-created_at'],
            },
        ),
    ]
