# Generated by Django 5.2.5 on 2025-08-20 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('merchant_account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='商品名稱')),
                ('description', models.TextField(verbose_name='商品介紹')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='商品價格')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='商品圖片網址')),
                ('phone_number', models.CharField(max_length=20, verbose_name='電話號碼')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='創建時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否上架')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchant_account.merchant', verbose_name='商家')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
                'ordering': ['-created_at'],
            },
        ),
    ]
