# Generated by Django 5.2.5 on 2025-09-03 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchant_marketplace", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="verification_timing",
            field=models.CharField(
                choices=[
                    ("before_payment", "付款前驗證"),
                    ("before_redeem", "核銷前驗證"),
                    ("after_redeem", "核銷後驗證"),
                ],
                default="before_redeem",
                max_length=20,
                verbose_name="驗證時間點",
            ),
        ),
    ]
