# Generated by Django 5.2.5 on 2025-09-09 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchant_marketplace", "0002_product_verification_timing"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="ticket_expiry",
            field=models.DateTimeField(
                blank=True,
                help_text="設定此商品票券的有效期限，留空則使用系統預設值",
                null=True,
                verbose_name="票券有效期限",
            ),
        ),
    ]
