# Generated by Django 5.2.5 on 2025-08-25 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_marketplace', '0002_remove_product_image_url_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(verbose_name='商品價格'),
        ),
    ]
