# Generated by Django 5.2.5 on 2025-09-17 07:05

import merchant_marketplace.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_marketplace', '0003_product_ticket_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='支援 JPG、PNG、GIF、WebP 格式，檔案大小不超過 5MB，尺寸建議在 100px-4096px 之間', null=True, upload_to='products/', validators=[merchant_marketplace.validators.validate_image_file], verbose_name='商品圖片'),
        ),
    ]
