# Generated by Django 5.2.5 on 2025-09-01 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_marketplace', '0003_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=1, verbose_name='庫存數量'),
        ),
    ]
