# Generated by Django 5.2.5 on 2025-09-18 04:09

import merchant_marketplace.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_marketplace', '0004_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='支援 JPG、PNG、GIF、WebP 格式，檔案大小不超過 5MB', null=True, upload_to='products/', validators=[merchant_marketplace.validators.validate_image_file], verbose_name='商品圖片'),
        ),
    ]
