# Generated by Django 5.2.5 on 2025-08-25 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers_account', '0003_purchaserecord_customer'),
        ('merchant_marketplace', '0002_remove_product_image_url_product_image'),
        ('newebpay', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='數量')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='購買時單價')),
                ('payment_provider', models.CharField(choices=[('newebpay', '藍新金流'), ('linepay', 'LinePay')], default='newebpay', max_length=20, verbose_name='付款服務提供者')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers_account.customer', verbose_name='消費者')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='newebpay.payment', to_field='merchant_order_no', verbose_name='付款記錄')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchant_marketplace.product', verbose_name='商品')),
            ],
            options={
                'verbose_name': '訂單項目',
                'verbose_name_plural': '訂單項目',
                'ordering': ['-payment__created_at'],
            },
        ),
    ]
