# Generated by Django 5.2.5 on 2025-09-03 06:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ShopName', models.CharField(max_length=50)),
                ('UnifiedNumber', models.CharField(max_length=8)),
                ('NationalNumber', models.CharField(max_length=10)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Name', models.CharField(max_length=30)),
                ('Address', models.CharField(max_length=50)),
                ('Cellphone', models.CharField(max_length=15)),
                ('Password', models.CharField(max_length=128)),
                ('subdomain', models.SlugField(unique=True)),
                ('member', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='會員帳號')),
            ],
        ),
    ]
