# Generated by Django 5.2.5 on 2025-09-19 09:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ShopName', models.CharField(max_length=50)),
                ('UnifiedNumber', models.CharField(max_length=8)),
                ('NationalNumber', models.CharField(max_length=10)),
                ('Name', models.CharField(max_length=30)),
                ('Address', models.CharField(max_length=50)),
                ('Cellphone', models.CharField(max_length=15)),
                ('subdomain', models.SlugField(unique=True)),
                ('verification_status', models.CharField(choices=[('pending', '待審核'), ('approved', '已通過'), ('rejected', '已拒絕'), ('suspended', '已暫停')], default='pending', help_text='商家身份驗證狀態', max_length=20, verbose_name='審核狀態')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='通過審核時間')),
                ('rejection_reason', models.TextField(blank=True, help_text='審核不通過時的原因說明', verbose_name='拒絕原因')),
                ('verification_documents', models.JSONField(blank=True, default=dict, help_text='儲存審核相關文件的元資料', verbose_name='驗證文件')),
                ('subdomain_change_count', models.PositiveIntegerField(default=0, help_text='本年度修改次數', verbose_name='修改次數')),
                ('last_subdomain_change', models.DateTimeField(blank=True, null=True, verbose_name='上次修改時間')),
                ('subdomain_history', models.JSONField(default=list, help_text='所有 subdomain 修改紀錄', verbose_name='修改歷史')),
                ('store_template_id', models.CharField(choices=[('modern_light', 'modern_light'), ('modern', 'modern'), ('tech', 'tech'), ('handcraft', 'handcraft'), ('vintage', 'vintage')], default='modern', help_text='選擇商店頁面的視覺風格樣式', max_length=20, verbose_name='商店模板風格')),
                ('member', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='會員帳號')),
            ],
        ),
        migrations.CreateModel(
            name='SubdomainRedirect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_subdomain', models.CharField(max_length=50, verbose_name='舊子網域')),
                ('new_subdomain', models.CharField(max_length=50, verbose_name='新子網域')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用中')),
                ('redirect_type', models.CharField(choices=[('301', '永久重導向'), ('302', '暫時重導向')], default='301', max_length=20, verbose_name='重導向類型')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(verbose_name='過期時間')),
                ('redirect_count', models.PositiveIntegerField(default=0, verbose_name='重導向次數')),
                ('last_used', models.DateTimeField(blank=True, null=True, verbose_name='最後使用時間')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subdomain_redirects', to='merchant_account.merchant', verbose_name='商家')),
            ],
            options={
                'verbose_name': '子網域重導向',
                'verbose_name_plural': '子網域重導向',
                'unique_together': {('old_subdomain', 'merchant')},
            },
        ),
    ]
