# Generated by Django 5.2.5 on 2025-09-18 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='store_template_id',
            field=models.CharField(choices=[('luxury', '奢華精品風'), ('modern', '現代簡約風'), ('tech', '科技數位風'), ('handcraft', '手工藝術風'), ('vintage', '復古經典風')], default='modern', help_text='選擇商店頁面的視覺風格樣式', max_length=20, verbose_name='商店模板風格'),
        ),
    ]
