# Generated by Django 5.2.5 on 2025-08-20 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='subdomain',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
