# Generated by Django 5.2.5 on 2025-09-04 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchant',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='Password',
        ),
    ]
