# Generated by Django 5.2.5 on 2025-08-21 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_account', '0002_merchant_subdomain'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='merchant_domain',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='自訂域名'),
        ),
        migrations.AddField(
            model_name='merchant',
            name='use_merchant_domain',
            field=models.BooleanField(default=False, verbose_name='使用自訂域名'),
        ),
    ]
