# Generated by Django 5.2.5 on 2025-09-08 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_account', '0002_remove_merchant_email_remove_merchant_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='last_subdomain_change',
            field=models.DateTimeField(blank=True, null=True, verbose_name='上次修改時間'),
        ),
        migrations.AddField(
            model_name='merchant',
            name='subdomain_change_count',
            field=models.PositiveIntegerField(default=0, help_text='本年度修改次數', verbose_name='修改次數'),
        ),
        migrations.AddField(
            model_name='merchant',
            name='subdomain_history',
            field=models.JSONField(default=list, help_text='所有 subdomain 修改紀錄', verbose_name='修改歷史'),
        ),
        migrations.CreateModel(
            name='SubdomainRedirect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_subdomain', models.CharField(max_length=50, verbose_name='舊子網域')),
                ('new_subdomain', models.CharField(max_length=50, verbose_name='新子網域')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用中')),
                ('redirect_type', models.CharField(choices=[('301', '永久重導向'), ('302', '暫時重導向')], default='301', max_length=20, verbose_name='重導向類型')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(verbose_name='過期時間')),
                ('redirect_count', models.PositiveIntegerField(default=0, verbose_name='重導向次數')),
                ('last_used', models.DateTimeField(blank=True, null=True, verbose_name='最後使用時間')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subdomain_redirects', to='merchant_account.merchant', verbose_name='商家')),
            ],
            options={
                'verbose_name': '子網域重導向',
                'verbose_name_plural': '子網域重導向',
                'unique_together': {('old_subdomain', 'merchant')},
            },
        ),
    ]
