# Generated by Django 5.2.5 on 2025-09-20 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_account', '0002_merchant_store_template_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='store_template_id',
            field=models.CharField(choices=[('modern_light', 'modern_light'), ('modern', 'modern'), ('tech', 'tech'), ('handcraft', 'handcraft'), ('vintage', 'vintage')], default='modern', help_text='選擇商店頁面的視覺風格樣式', max_length=20, verbose_name='商店模板風格'),
        ),
    ]
