# Generated by Django 5.2.5 on 2025-09-23 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_account', '0003_alter_merchant_store_template_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='UnifiedNumber',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
