# Generated by Django 5.2.5 on 2025-09-01 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_account', '0003_merchant_merchant_domain_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchant',
            name='merchant_domain',
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='use_merchant_domain',
        ),
        migrations.AlterField(
            model_name='merchant',
            name='subdomain',
            field=models.SlugField(default='temp', unique=True),
            preserve_default=False,
        ),
    ]
