# Generated by Django 5.2.5 on 2025-09-09 02:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_account', '0003_merchant_last_subdomain_change_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantOwnDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(help_text='例如: www.shop.com 或 shop.com', max_length=253, unique=True, verbose_name='網域名稱')),
                ('is_verified', models.BooleanField(default=False, verbose_name='已驗證')),
                ('verification_token', models.CharField(blank=True, max_length=64, verbose_name='驗證Token')),
                ('verification_method', models.CharField(choices=[('DNS', 'DNS記錄驗證'), ('FILE', '檔案驗證')], default='DNS', max_length=10, verbose_name='驗證方式')),
                ('ssl_enabled', models.BooleanField(default=False, verbose_name='SSL已啟用')),
                ('ssl_certificate_expires', models.DateTimeField(blank=True, null=True, verbose_name='SSL證書到期時間')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用中')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='驗證時間')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='own_domains', to='merchant_account.merchant', verbose_name='商家')),
            ],
            options={
                'verbose_name': '商家自有網域',
                'verbose_name_plural': '商家自有網域',
                'ordering': ['-created_at'],
            },
        ),
    ]
