# Generated by Django 5.2.5 on 2025-08-30 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_account', '0003_merchant_merchant_domain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='linepay_channel_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='LINE Pay Channel ID'),
        ),
        migrations.AddField(
            model_name='merchant',
            name='linepay_channel_secret',
            field=models.TextField(blank=True, verbose_name='LINE Pay Channel Secret(加密)'),
        ),
        migrations.AddField(
            model_name='merchant',
            name='newebpay_hash_iv',
            field=models.TextField(blank=True, verbose_name='藍新金流HashIV(加密)'),
        ),
        migrations.AddField(
            model_name='merchant',
            name='newebpay_hash_key',
            field=models.TextField(blank=True, verbose_name='藍新金流HashKey(加密)'),
        ),
        migrations.AddField(
            model_name='merchant',
            name='newebpay_merchant_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='藍新金流商店代號'),
        ),
        migrations.AddField(
            model_name='merchant',
            name='payment_setup_completed',
            field=models.BooleanField(default=False, verbose_name='金流設定完成'),
        ),
    ]
