# Generated by Django 5.2.5 on 2025-09-01 06:02

from django.db import migrations, models
from merchant_account.utils import generate_unique_subdomain


def generate_subdomains_for_null_merchants(apps, schema_editor):
    Merchant = apps.get_model("merchant_account", "Merchant")
    for merchant in Merchant.objects.filter(subdomain__in=[None, ""]):
        merchant.subdomain = generate_unique_subdomain()
        merchant.save()


class Migration(migrations.Migration):

    dependencies = [
        ("merchant_account", "0003_merchant_merchant_domain_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="merchant",
            name="merchant_domain",
        ),
        migrations.RemoveField(
            model_name="merchant",
            name="use_merchant_domain",
        ),
        migrations.RunPython(generate_subdomains_for_null_merchants),
        migrations.AlterField(
            model_name="merchant",
            name="subdomain",
            field=models.SlugField(unique=True),
            preserve_default=False,
        ),
    ]
