# Generated by Django 5.2.5 on 2025-09-16 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_account', '0004_merchantowndomain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchantowndomain',
            name='ssl_certificate_expires',
        ),
        migrations.RemoveField(
            model_name='merchantowndomain',
            name='ssl_enabled',
        ),
        migrations.RemoveField(
            model_name='merchantowndomain',
            name='verification_method',
        ),
        migrations.RemoveField(
            model_name='merchantowndomain',
            name='verification_token',
        ),
        migrations.AddField(
            model_name='merchantowndomain',
            name='cloudflare_record_id',
            field=models.CharField(blank=True, help_text='用於刪除或修改 DNS 記錄', max_length=100, verbose_name='Cloudflare 記錄 ID'),
        ),
        migrations.AddField(
            model_name='merchantowndomain',
            name='cname_target',
            field=models.CharField(blank=True, help_text='指向的子網域，如: shop123.truepay.tw', max_length=253, verbose_name='CNAME 目標'),
        ),
    ]
