# Generated by Django 5.2.5 on 2025-09-16 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_account', '0004_merchantowndomain'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='審核不通過時的原因說明', verbose_name='拒絕原因'),
        ),
        migrations.AddField(
            model_name='merchant',
            name='verification_documents',
            field=models.JSONField(blank=True, default=dict, help_text='儲存審核相關文件的元資料', verbose_name='驗證文件'),
        ),
        migrations.AddField(
            model_name='merchant',
            name='verification_status',
            field=models.CharField(choices=[('pending', '待審核'), ('approved', '已通過'), ('rejected', '已拒絕'), ('suspended', '已暫停')], default='pending', help_text='商家身份驗證狀態', max_length=20, verbose_name='審核狀態'),
        ),
        migrations.AddField(
            model_name='merchant',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='通過審核時間'),
        ),
    ]
