# Generated by Django 5.2.5 on 2025-09-16 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_account', '0005_remove_merchantowndomain_ssl_certificate_expires_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MerchantOwnDomain',
        ),
    ]
