# Generated by Django 5.2.5 on 2025-09-18 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_account', '0005_add_merchant_verification'),
        ('merchant_account', '0006_remove_merchant_own_domain'),
    ]

    operations = [
    ]
